# Info about these TOML files:
# https://www.netlify.com/docs/netlify-toml-reference/

[build]
functions = "lambda"

environment = { DB_USER = "biflpkhu", DB_HOST = "baasu.db.elephantsql.com", DB_DATABASE =  "biflpkhu", DB_PASSWORD =  "hmkS-pad-WLwC-6weDRnFsFJweRkwk21", DB_PORT = 5432 }